export const GET_PLANETS = "GET_PLANETS";
export const GET_VEHICLES = "GET_VEHICLES";
export const SET_LOADING = "SET_LOADING";
export const GET_PLANETS_ERROR = "GET_PLANETS_ERROR";
export const SELECT_PLANET = "SELECT_PLANET";
export const REMOVE_PLANET = "REMOVE_PLANET";
